import 'package:flutter/material.dart';
import 'package:tasker/emoji_text.dart';
import 'package:tasker/models/emoji_model.dart';

import 'helper_class.dart';

List<Tags> tags = [
  Tags(lookTitle: "Hot", lookColor: Colors.red),
  Tags(lookTitle: "Smart", lookColor: Colors.blue),
  Tags(lookTitle: "Rich", lookColor: Colors.green),
  Tags(lookTitle: "Alpha", lookColor: Colors.yellow),
  Tags(lookTitle: "Funny", lookColor: Colors.purple),
  Tags(lookTitle: "Confident", lookColor: Colors.amber),
  Tags(lookTitle: "Rich", lookColor: Colors.blue),
  Tags(lookTitle: "Outgoing", lookColor: Colors.grey),
  Tags(lookTitle: "Introvert", lookColor: Colors.black),
  Tags(lookTitle: "Best", lookColor: Colors.brown),
];

List<EmojiModel> emojisSet = [
  EmojiModel(emoji: "😀", isSelected: false),
  EmojiModel(emoji: "😃", isSelected: false),
  EmojiModel(emoji: "😄", isSelected: false),
  EmojiModel(emoji: "😁", isSelected: false),
  EmojiModel(emoji: "😆", isSelected: false),
  EmojiModel(emoji: "😅", isSelected: false),
  EmojiModel(emoji: "😂", isSelected: false),
  EmojiModel(emoji: "🤣", isSelected: false),
  EmojiModel(emoji: "🥲", isSelected: false),
  EmojiModel(emoji: "😊", isSelected: false),
  EmojiModel(emoji: "😇", isSelected: false),
  EmojiModel(emoji: "🙂", isSelected: false),
  EmojiModel(emoji: "🙃", isSelected: false),
  EmojiModel(emoji: "😉", isSelected: false),
  EmojiModel(emoji: "😌", isSelected: false),
  EmojiModel(emoji: "😍", isSelected: false),
  EmojiModel(emoji: "🥰", isSelected: false),
  EmojiModel(emoji: "😘", isSelected: false),
  EmojiModel(emoji: "😗", isSelected: false),
  EmojiModel(emoji: "😙", isSelected: false),
  EmojiModel(emoji: "😚", isSelected: false),
  EmojiModel(emoji: "😋", isSelected: false),
  EmojiModel(emoji: "😛", isSelected: false),
  EmojiModel(emoji: "😝", isSelected: false),
  EmojiModel(emoji: "😜", isSelected: false),
  EmojiModel(emoji: "🤪", isSelected: false),
  EmojiModel(emoji: "🤨", isSelected: false),
  EmojiModel(emoji: "🧐", isSelected: false),
  EmojiModel(emoji: "🤓", isSelected: false),
  EmojiModel(emoji: "😎", isSelected: false),
  EmojiModel(emoji: "🥸", isSelected: false),
  EmojiModel(emoji: "🤩", isSelected: false),
  EmojiModel(emoji: "🥳", isSelected: false),
  EmojiModel(emoji: "😏", isSelected: false),
  EmojiModel(emoji: "😒", isSelected: false),
  EmojiModel(emoji: "😞", isSelected: false),
  EmojiModel(emoji: "😔", isSelected: false),
  EmojiModel(emoji: "😟", isSelected: false),
  EmojiModel(emoji: "😕", isSelected: false),
  EmojiModel(emoji: "🙁", isSelected: false),
  EmojiModel(emoji: "😣", isSelected: false),
  EmojiModel(emoji: "😖", isSelected: false),
  EmojiModel(emoji: "😫", isSelected: false),
  EmojiModel(emoji: "😩", isSelected: false),
  EmojiModel(emoji: "🥺", isSelected: false),
  EmojiModel(emoji: "😢", isSelected: false),
  EmojiModel(emoji: "😭", isSelected: false),
  EmojiModel(emoji: "😤", isSelected: false),
  EmojiModel(emoji: "😠", isSelected: false),
  EmojiModel(emoji: "😡", isSelected: false),
  EmojiModel(emoji: "🤬", isSelected: false),
  EmojiModel(emoji: "🤯", isSelected: false),
  EmojiModel(emoji: "😳", isSelected: false),
  EmojiModel(emoji: "🥵", isSelected: false),
  EmojiModel(emoji: "🥶", isSelected: false),
  EmojiModel(emoji: "😱", isSelected: false),
  EmojiModel(emoji: "😨", isSelected: false),
  EmojiModel(emoji: "😰", isSelected: false),
  EmojiModel(emoji: "😥", isSelected: false),
  EmojiModel(emoji: "😓", isSelected: false),
  EmojiModel(emoji: "🤗", isSelected: false),
  EmojiModel(emoji: "🤔", isSelected: false),
  EmojiModel(emoji: "🤭", isSelected: false),
  EmojiModel(emoji: "🤫", isSelected: false),
  EmojiModel(emoji: "🤥", isSelected: false),
  EmojiModel(emoji: "😶", isSelected: false),
  EmojiModel(emoji: "😐", isSelected: false),
  EmojiModel(emoji: "😑", isSelected: false),
  EmojiModel(emoji: "😬", isSelected: false),
  EmojiModel(emoji: "🙄", isSelected: false),
  EmojiModel(emoji: "😯", isSelected: false),
  EmojiModel(emoji: "😦", isSelected: false),
  EmojiModel(emoji: "😧", isSelected: false),
  EmojiModel(emoji: "😮", isSelected: false),
  EmojiModel(emoji: "😲", isSelected: false),
  EmojiModel(emoji: "🥱", isSelected: false),
  EmojiModel(emoji: "😴", isSelected: false),
  EmojiModel(emoji: "🤤", isSelected: false),
  EmojiModel(emoji: "😪", isSelected: false),
  EmojiModel(emoji: "😵", isSelected: false),
  EmojiModel(emoji: "🤐", isSelected: false),
  EmojiModel(emoji: "🥴", isSelected: false),
  EmojiModel(emoji: "🤢", isSelected: false),
  EmojiModel(emoji: "🤮", isSelected: false),
  EmojiModel(emoji: "🤧", isSelected: false),
  EmojiModel(emoji: "😷", isSelected: false),
  EmojiModel(emoji: "🤒", isSelected: false),
  EmojiModel(emoji: "🤕", isSelected: false),
  EmojiModel(emoji: "🤑", isSelected: false),
  EmojiModel(emoji: "🤠", isSelected: false),
  EmojiModel(emoji: "😈", isSelected: false),
  EmojiModel(emoji: "👿", isSelected: false),
  EmojiModel(emoji: "👹", isSelected: false),
  EmojiModel(emoji: "👺", isSelected: false),
  EmojiModel(emoji: "🤡", isSelected: false),
  EmojiModel(emoji: "💩", isSelected: false),
  EmojiModel(emoji: "👻", isSelected: false),
  EmojiModel(emoji: "💀", isSelected: false),
  EmojiModel(emoji: "👽", isSelected: false),
  EmojiModel(emoji: "👾", isSelected: false),
  EmojiModel(emoji: "🤖", isSelected: false),
  EmojiModel(emoji: "🎃", isSelected: false),
  EmojiModel(emoji: "😺", isSelected: false),
  EmojiModel(emoji: "😸", isSelected: false),
  EmojiModel(emoji: "😹", isSelected: false),
  EmojiModel(emoji: "😻", isSelected: false),
  EmojiModel(emoji: "😼", isSelected: false),
  EmojiModel(emoji: "😽", isSelected: false),
  EmojiModel(emoji: "🙀", isSelected: false),
  EmojiModel(emoji: "😿", isSelected: false),
  EmojiModel(emoji: "😾", isSelected: false),
  EmojiModel(emoji: "👋", isSelected: false),
  EmojiModel(emoji: "🤚", isSelected: false),
  EmojiModel(emoji: "🖐", isSelected: false),
  EmojiModel(emoji: "✋", isSelected: false),
  EmojiModel(emoji: "🖖", isSelected: false),
  EmojiModel(emoji: "👌", isSelected: false),
  EmojiModel(emoji: "🤌", isSelected: false),
  EmojiModel(emoji: "🤏", isSelected: false),
  EmojiModel(emoji: "🤞", isSelected: false),
  EmojiModel(emoji: "🤟", isSelected: false),
  EmojiModel(emoji: "🤘", isSelected: false),
  EmojiModel(emoji: "🤙", isSelected: false),
  EmojiModel(emoji: "👈", isSelected: false),
  EmojiModel(emoji: "👉", isSelected: false),
  EmojiModel(emoji: "👆", isSelected: false),
  EmojiModel(emoji: "🖕", isSelected: false),
  EmojiModel(emoji: "👇", isSelected: false),
  EmojiModel(emoji: '👍', isSelected: false),
  EmojiModel(emoji: "👎", isSelected: false),
  EmojiModel(emoji: '✊', isSelected: false),
  EmojiModel(emoji: "👊", isSelected: false),
  EmojiModel(emoji: "🤛", isSelected: false),
  EmojiModel(emoji: "🤜", isSelected: false),
  EmojiModel(emoji: "👏", isSelected: false),
  EmojiModel(emoji: "🙌", isSelected: false),
  EmojiModel(emoji: "👐", isSelected: false),
  EmojiModel(emoji: "🤲", isSelected: false),
  EmojiModel(emoji: "🤝", isSelected: false),
  EmojiModel(emoji: "🙏", isSelected: false),
  EmojiModel(emoji: "💅", isSelected: false),
  EmojiModel(emoji: "🤳", isSelected: false),
  EmojiModel(emoji: "💪", isSelected: false),
  EmojiModel(emoji: "🦾", isSelected: false),
  EmojiModel(emoji: "🦵", isSelected: false),
  EmojiModel(emoji: "🦿", isSelected: false),
  EmojiModel(emoji: "🦶", isSelected: false),
  EmojiModel(emoji: "👣", isSelected: false),
  EmojiModel(emoji: "👂", isSelected: false),
  EmojiModel(emoji: "🦻", isSelected: false),
  EmojiModel(emoji: "👃", isSelected: false),
  EmojiModel(emoji: "🫀", isSelected: false),
  EmojiModel(emoji: "🫁", isSelected: false),
  EmojiModel(emoji: "🧠", isSelected: false),
  EmojiModel(emoji: "🦷", isSelected: false),
  EmojiModel(emoji: "🦴", isSelected: false),
  EmojiModel(emoji: "👀", isSelected: false),
  EmojiModel(emoji: "👁", isSelected: false),
  EmojiModel(emoji: "👅", isSelected: false),
  EmojiModel(emoji: "👄", isSelected: false),
  EmojiModel(emoji: "💋", isSelected: false),
  EmojiModel(emoji: "🩸", isSelected: false),
  EmojiModel(emoji: "🔴", isSelected: false),
  EmojiModel(emoji: "🟠", isSelected: false),
  EmojiModel(emoji: "🟡", isSelected: false),
  EmojiModel(emoji: "🟢", isSelected: false),
  EmojiModel(emoji: "🔵", isSelected: false),
  EmojiModel(emoji: "🟣", isSelected: false),
  EmojiModel(emoji: "⚫️", isSelected: false),
  EmojiModel(emoji: "⚪️", isSelected: false),
  EmojiModel(emoji: "🟤", isSelected: false),
  EmojiModel(emoji: "🔺", isSelected: false),
  EmojiModel(emoji: "🔻", isSelected: false),
  EmojiModel(emoji: "❌", isSelected: false),
  EmojiModel(emoji: "⭕️", isSelected: false),
  EmojiModel(emoji: "🛑", isSelected: false),
  EmojiModel(emoji: "⛔️", isSelected: false),
  EmojiModel(emoji: "📛", isSelected: false),
  EmojiModel(emoji: "🚫", isSelected: false),
  EmojiModel(emoji: "💯", isSelected: false),
];
List<Ratings> ratings = [
  Ratings(
    ratingTitle: "Looks",
    ratingScore: "8",
  ),
  Ratings(
    ratingTitle: "Personality",
    ratingScore: "9",
  ),
  Ratings(
    ratingTitle: "Fun",
    ratingScore: "7",
  ),
  Ratings(
    ratingTitle: "Intelligence",
    ratingScore: "8",
  ),
  Ratings(
    ratingTitle: "Successful",
    ratingScore: "9",
  ),
  Ratings(
    ratingTitle: "Humor",
    ratingScore: "9",
  ),
  Ratings(
    ratingTitle: "Compatibility",
    ratingScore: "8",
  ),
];
